### Numpy (part 3)

In [1]:
import numpy as np

In [2]:
# Numpy - Array Manipulation.

In [3]:
arr = np.random.randint(1,10,(4,4))

In [4]:
arr

array([[6, 3, 2, 7],
       [5, 9, 6, 5],
       [2, 8, 3, 8],
       [2, 2, 2, 4]])

In [5]:
arr.reshape(8,2)

array([[6, 3],
       [2, 7],
       [5, 9],
       [6, 5],
       [2, 8],
       [3, 8],
       [2, 2],
       [2, 4]])

In [6]:
arr

array([[6, 3, 2, 7],
       [5, 9, 6, 5],
       [2, 8, 3, 8],
       [2, 2, 2, 4]])

In [7]:
arr.T

array([[6, 5, 2, 2],
       [3, 9, 8, 2],
       [2, 6, 3, 2],
       [7, 5, 8, 4]])

In [8]:
arr.flatten()

array([6, 3, 2, 7, 5, 9, 6, 5, 2, 8, 3, 8, 2, 2, 2, 4])

In [9]:
arr

array([[6, 3, 2, 7],
       [5, 9, 6, 5],
       [2, 8, 3, 8],
       [2, 2, 2, 4]])

In [10]:
np.expand_dims(arr,axis=1) # Column-wise dimension increament

array([[[6, 3, 2, 7]],

       [[5, 9, 6, 5]],

       [[2, 8, 3, 8]],

       [[2, 2, 2, 4]]])

In [11]:
np.expand_dims(arr,axis=0) # Row-wise dimension increament

array([[[6, 3, 2, 7],
        [5, 9, 6, 5],
        [2, 8, 3, 8],
        [2, 2, 2, 4]]])

In [12]:
data = np.array([[1] , [2] , [3]])

In [13]:
data

array([[1],
       [2],
       [3]])

In [14]:
# Remove axes of length one from `a`.
np.squeeze(data)

array([1, 2, 3])

In [15]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [16]:
data

array([[1],
       [2],
       [3]])

In [17]:
# Roll array elements along a given axis.
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [18]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [19]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
# Numpy - Binary Operators

In [21]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [22]:
arr1

array([[1, 5, 1, 6],
       [6, 3, 8, 9],
       [2, 3, 2, 2]])

In [23]:
arr2

array([[1, 7, 9, 3],
       [9, 8, 3, 3],
       [3, 7, 3, 9]])

In [24]:
arr1+arr2

array([[ 2, 12, 10,  9],
       [15, 11, 11, 12],
       [ 5, 10,  5, 11]])

In [25]:
arr1*arr2

array([[ 1, 35,  9, 18],
       [54, 24, 24, 27],
       [ 6, 21,  6, 18]])

In [26]:
arr1/arr2

array([[1.        , 0.71428571, 0.11111111, 2.        ],
       [0.66666667, 0.375     , 2.66666667, 3.        ],
       [0.66666667, 0.42857143, 0.66666667, 0.22222222]])

In [27]:
arr1**arr2

array([[       1,    78125,        1,      216],
       [10077696,     6561,      512,      729],
       [       8,     2187,        8,      512]])

In [28]:
~arr1

array([[ -2,  -6,  -2,  -7],
       [ -7,  -4,  -9, -10],
       [ -3,  -4,  -3,  -3]])

In [29]:
arr1

array([[1, 5, 1, 6],
       [6, 3, 8, 9],
       [2, 3, 2, 2]])

In [30]:
arr1>arr2

array([[False, False, False,  True],
       [False, False,  True,  True],
       [False, False, False, False]])

In [31]:
# Numpy - String Functions.

In [32]:
arr = np.array(["subhan" , "reza"])

In [33]:
arr

array(['subhan', 'reza'], dtype='<U6')

In [34]:
np.char.upper(arr)

array(['SUBHAN', 'REZA'], dtype='<U6')

In [35]:
np.char.capitalize(arr)

array(['Subhan', 'Reza'], dtype='<U6')

In [36]:
np.char.title(arr)

array(['Subhan', 'Reza'], dtype='<U6')

In [37]:
# Numpy - Mathematical Functions.

In [38]:
arr1

array([[1, 5, 1, 6],
       [6, 3, 8, 9],
       [2, 3, 2, 2]])

In [39]:
np.sin(arr1)

array([[ 0.84147098, -0.95892427,  0.84147098, -0.2794155 ],
       [-0.2794155 ,  0.14112001,  0.98935825,  0.41211849],
       [ 0.90929743,  0.14112001,  0.90929743,  0.90929743]])

In [40]:
np.cos(arr1)

array([[ 0.54030231,  0.28366219,  0.54030231,  0.96017029],
       [ 0.96017029, -0.9899925 , -0.14550003, -0.91113026],
       [-0.41614684, -0.9899925 , -0.41614684, -0.41614684]])

In [41]:
np.tan(arr1)

array([[ 1.55740772, -3.38051501,  1.55740772, -0.29100619],
       [-0.29100619, -0.14254654, -6.79971146, -0.45231566],
       [-2.18503986, -0.14254654, -2.18503986, -2.18503986]])

In [42]:
np.log10(arr1)

array([[0.        , 0.69897   , 0.        , 0.77815125],
       [0.77815125, 0.47712125, 0.90308999, 0.95424251],
       [0.30103   , 0.47712125, 0.30103   , 0.30103   ]])

In [43]:
np.exp(arr1)

array([[2.71828183e+00, 1.48413159e+02, 2.71828183e+00, 4.03428793e+02],
       [4.03428793e+02, 2.00855369e+01, 2.98095799e+03, 8.10308393e+03],
       [7.38905610e+00, 2.00855369e+01, 7.38905610e+00, 7.38905610e+00]])

In [44]:
np.power(arr1,2)

array([[ 1, 25,  1, 36],
       [36,  9, 64, 81],
       [ 4,  9,  4,  4]], dtype=int32)

In [45]:
np.mean(arr1)

4.0

In [46]:
np.median(arr1)

3.0

In [47]:
np.std(arr1)

2.614064523559687

In [48]:
np.var(arr1)

6.833333333333333

In [49]:
np.min(arr1)

1

In [50]:
np.max(arr1)

9

In [51]:
# Numpy - Arithmetic Operations.

In [52]:
arr1

array([[1, 5, 1, 6],
       [6, 3, 8, 9],
       [2, 3, 2, 2]])

In [53]:
arr2

array([[1, 7, 9, 3],
       [9, 8, 3, 3],
       [3, 7, 3, 9]])

In [54]:
arr1-arr2

array([[ 0, -2, -8,  3],
       [-3, -5,  5,  6],
       [-1, -4, -1, -7]])

In [55]:
np.subtract(arr1,arr2)

array([[ 0, -2, -8,  3],
       [-3, -5,  5,  6],
       [-1, -4, -1, -7]])

In [56]:
np.multiply(arr1,arr2)

array([[ 1, 35,  9, 18],
       [54, 24, 24, 27],
       [ 6, 21,  6, 18]])

In [57]:
np.mod(arr1,arr2)

array([[0, 5, 1, 0],
       [6, 3, 2, 0],
       [2, 3, 2, 2]])

In [58]:
np.power(arr1,arr2)

array([[       1,    78125,        1,      216],
       [10077696,     6561,      512,      729],
       [       8,     2187,        8,      512]])

In [59]:
np.sqrt(arr1)

array([[1.        , 2.23606798, 1.        , 2.44948974],
       [2.44948974, 1.73205081, 2.82842712, 3.        ],
       [1.41421356, 1.73205081, 1.41421356, 1.41421356]])

In [60]:
# Numpy - Statistical Functions.

In [61]:
arr1

array([[1, 5, 1, 6],
       [6, 3, 8, 9],
       [2, 3, 2, 2]])

In [62]:
np.mean(arr1)

4.0

In [63]:
np.std(arr1)

2.614064523559687

In [64]:
np.median(arr1)

3.0

### Numpy (part 4)

In [65]:
## Sort, Search & Counting Functions.

In [66]:
arr = np.array([4,2,8,5,3,9,12,56])

In [67]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [68]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [69]:
# Find indices where elements should be inserted to maintain order.
np.searchsorted(arr,6)

5

In [70]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [71]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [72]:
np.count_nonzero(arr1)

6

In [73]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [74]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [75]:
# Numpy - Byte Swapping.

In [76]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [77]:
arr.byteswap(True)

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [78]:
arr

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [79]:
# Numpy - Copies &Views.

In [80]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [81]:
a = np.copy(arr1)

In [82]:
b = arr1.view()

In [83]:
b = arr1

In [84]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [85]:
b[0] = 234

In [86]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [87]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [88]:
# Numpy - Matrix Library.

In [89]:
import numpy.matlib as nm

In [90]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [91]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [92]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [93]:
# Numpy - Linear Algebra

In [100]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [101]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [102]:
arr1

array([[0, 0],
       [1, 2]])

In [103]:
arr2

array([[3, 1],
       [0, 4]])

In [104]:
np.dot(arr1,arr2)

array([[0, 0],
       [3, 9]])

In [105]:
arr1@arr2

array([[0, 0],
       [3, 9]])