### Numpy (Part 1)

<span style = 'font-size:0.8em;'>
NumPy is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in scientific computing, data analysis, and machine learning.

Here's a brief overview of some of the key features of NumPy:

1. **Arrays**: NumPy's main object is the `ndarray`, a multi-dimensional array. These arrays can be created from Python lists or other sequences and provide efficient storage and manipulation of data.

2. **Array Operations**: NumPy provides a wide range of mathematical functions that operate element-wise on arrays. These include basic arithmetic operations, trigonometric functions, statistical functions, and more.

3. **Broadcasting**: NumPy's broadcasting capability allows arithmetic operations to be performed on arrays of different shapes. When operating on two arrays, NumPy compares their shapes element-wise and performs the operation if the shapes are compatible.

4. **Indexing and Slicing**: NumPy arrays can be sliced and indexed to access subsets of the data efficiently. This includes basic slicing, advanced indexing, and boolean indexing.

5. **Linear Algebra**: NumPy provides a rich set of functions for linear algebra operations, such as matrix multiplication, eigenvalue decomposition, singular value decomposition, and solving linear equations.

6. **Random Number Generation**: NumPy includes a random number generation module that can generate random numbers from various probability distributions.

7. **Integration with Other Libraries**: NumPy integrates well with other Python libraries such as SciPy, matplotlib, and pandas, providing a solid foundation for scientific computing and data analysis.

Overall, NumPy is an essential tool for any Python programmer working with numerical data, offering both performance and flexibility.
</span>

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [8]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
arr.ndim

1

In [10]:
arr1.ndim

2

In [12]:
# matrix will have min 2 dimension at any point of time
mat = np.matrix(l)

In [13]:
mat

matrix([[1, 2, 3, 4, 5]])

In [14]:
# asanyarray convert anything to array
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [15]:
# mat is itself an array so can't change
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
# shallow copy operation
a = arr

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
arr[0] = 100

In [21]:
arr

array([100,   2,   3,   4,   5])

In [22]:
a

array([100,   2,   3,   4,   5])

In [23]:
# deep copy
b = np.copy(arr)

In [24]:
b

array([100,   2,   3,   4,   5])

In [25]:
b[0] = 234

In [26]:
b

array([234,   2,   3,   4,   5])

In [27]:
arr

array([100,   2,   3,   4,   5])

In [28]:
# Construct an array by executing a function over each coordinate.
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [31]:
iterable = (i*i for i in range(5))

In [32]:
# Create a new 1-dimensional array from an iterable object.
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring("23 45 56",sep = ' ')

array([23., 45., 56.])

In [34]:
np.fromstring('23,45,56',sep  = ',' )

array([23., 45., 56.])

In [35]:
arr

array([100,   2,   3,   4,   5])

In [36]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [37]:
arr.ndim

1

In [38]:
arr1.ndim

2

In [39]:
arr.size

5

In [40]:
# size of an array
arr1.size

6

In [41]:
# dimension of an array 
arr.shape

(5,)

In [42]:
arr1.shape

(2, 3)

In [43]:
arr.dtype

dtype('int32')

In [44]:
arr1.dtype

dtype('int32')

### Part 2

In [45]:
range(5)

range(0, 5)

In [46]:
list(range(5))

[0, 1, 2, 3, 4]

In [47]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
# list(range(0.4,10.4))
# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[48], line 1
# ----> 1 list(range(0.4,10.4))

# TypeError: 'float' object cannot be interpreted as an integer

In [50]:
# generate sequence of floating point numbers
list(np.arange(.4 , 10.4 , 0.2)) # arange([start,] stop[, step,], dtype=None, *, like=None)


[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [51]:
# Return evenly spaced numbers over a specified interval.
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [52]:
# Return numbers spaced evenly on a log scale.
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [53]:
# Return a new array of given shape and type, filled with zeros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [57]:
# Return a new array of given shape and type, filled with ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [58]:
arr = np.ones((3,4))

In [59]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [61]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [62]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [63]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere(identity matix)
arr1 = np.eye(5)

In [64]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
import pandas as pd 

In [67]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [68]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``.
np.random.rand(2,3)

array([[0.07540861, 0.6552083 , 0.64242899],
       [0.11614633, 0.46095299, 0.51832279]])

In [70]:
 # generates an array of shape ``(d0, d1, ..., dn)``, filled
# with random floats sampled from a univariate "normal" (Gaussian)
# distribution of mean 0 and variance 1
np.random.randn(2,3)

array([[-0.50034593, -0.11070171,  1.71214353],
       [ 0.7416835 , -0.48185579,  1.18731735]])

In [71]:
arr2 = np.random.randint(1,5 , (3,4))

In [72]:
arr2

array([[3, 1, 1, 3],
       [3, 4, 3, 3],
       [4, 2, 4, 4]])

In [73]:
arr2.size

12

In [74]:
arr2.shape

(3, 4)

In [75]:
arr2

array([[3, 1, 1, 3],
       [3, 4, 3, 3],
       [4, 2, 4, 4]])

In [76]:
arr2.reshape(6,2)

array([[3, 1],
       [1, 3],
       [3, 4],
       [3, 3],
       [4, 2],
       [4, 4]])

In [77]:
arr2.reshape(2,6)

array([[3, 1, 1, 3, 3, 4],
       [3, 3, 4, 2, 4, 4]])

In [78]:
arr2.reshape(4,3)

array([[3, 1, 1],
       [3, 3, 4],
       [3, 3, 4],
       [2, 4, 4]])

In [79]:
arr2.reshape(4,-1)

array([[3, 1, 1],
       [3, 3, 4],
       [3, 3, 4],
       [2, 4, 4]])

In [80]:
arr2.reshape(4,-1432453453)

array([[3, 1, 1],
       [3, 3, 4],
       [3, 3, 4],
       [2, 4, 4]])

In [81]:
arr2.reshape(4,-2)

array([[3, 1, 1],
       [3, 3, 4],
       [3, 3, 4],
       [2, 4, 4]])

In [83]:
arr2.reshape(2,2,3)

array([[[3, 1, 1],
        [3, 3, 4]],

       [[3, 3, 4],
        [2, 4, 4]]])

In [84]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[3]]],


         [[[1]]],


         [[[1]]]],



        [[[[3]]],


         [[[3]]],


         [[[4]]]]],




       [[[[[3]]],


         [[[3]]],


         [[[4]]]],



        [[[[2]]],


         [[[4]]],


         [[[4]]]]]])

In [93]:
arr1 = np.random.randint(1,10 , (5,6))

In [94]:
arr1

array([[3, 4, 3, 1, 9, 8],
       [9, 1, 9, 8, 1, 1],
       [2, 5, 3, 1, 8, 3],
       [1, 9, 1, 3, 4, 7],
       [8, 3, 6, 2, 6, 7]])

In [95]:
arr1 >8

array([[False, False, False, False,  True, False],
       [ True, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False]])

In [96]:
arr1[arr1 >8]

array([9, 9, 9, 9])

In [97]:
arr1

array([[3, 4, 3, 1, 9, 8],
       [9, 1, 9, 8, 1, 1],
       [2, 5, 3, 1, 8, 3],
       [1, 9, 1, 3, 4, 7],
       [8, 3, 6, 2, 6, 7]])

In [98]:
# Extract 3,4 
arr1[0,[0,1]]

array([3, 4])

In [108]:
# Extract   3,1
#           1,3
arr1[2:4,[2,3]]

array([[3, 1],
       [1, 3]])

In [109]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [110]:
arr1

array([[2, 2, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [111]:
arr2

array([[1, 2, 2],
       [2, 1, 1],
       [1, 2, 2]])

In [112]:
arr1+arr2

array([[3, 4, 4],
       [3, 3, 3],
       [2, 3, 4]])

In [113]:
arr1-arr2

array([[ 1,  0,  0],
       [-1,  1,  1],
       [ 0, -1,  0]])

In [114]:
arr1

array([[2, 2, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [115]:
arr2

array([[1, 2, 2],
       [2, 1, 1],
       [1, 2, 2]])

In [116]:
arr1*arr2

array([[2, 4, 4],
       [2, 2, 2],
       [1, 2, 4]])

In [118]:
arr1/arr2

array([[2. , 1. , 1. ],
       [0.5, 2. , 2. ],
       [1. , 0.5, 1. ]])

In [117]:
# Matrix Multiplication
arr1@arr2

array([[ 8, 10, 10],
       [ 7,  8,  8],
       [ 5,  7,  7]])

In [119]:
arr1/0

C:\Users\sreza\AppData\Local\Temp\ipykernel_19612\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [120]:
# Numpy- Broadcasting

In [121]:
arr = np.zeros((3,4))

In [122]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [124]:
a = np.array([1,2,3,4])

In [125]:
# column wise addition
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [126]:
b = np.array([[3,4,5]])

In [127]:
b

array([[3, 4, 5]])

In [128]:
b.T

array([[3],
       [4],
       [5]])

In [129]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [130]:
arr+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [131]:
arr1 = arr+b.T

In [132]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [133]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [134]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [135]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [136]:
np.min(arr1)

3.0

In [137]:
np.max(arr1)

5.0